Description: An RDS DBCluster for the CloudFormation Workshop
Parameters:
  DBPwd: 
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$
  MinCapacity:
    Description: The Minimum Scaling Capacity
    Type: Number
  MaxCapacity:
    Description: The Maximum Scaling Capacity
    Type: Number
Resources:
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: 'adminUser'
      MasterUserPassword: !Ref DBPwd 
      DBClusterIdentifier: my-serverless-cluster
      Engine: aurora-postgresql
      EngineVersion: 10.7
      EngineMode: serverless
      DeletionProtection: True
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: !Ref MinCapacity
        MaxCapacity: !Ref MaxCapacity
        SecondsUntilAutoPause: 1000
  S3Bucket:
    Type: 'AWS::S3::Bucket'